---
.travis.yml:
  rvms:
  - 1.8.7
  - 1.9.3
  - ruby-head
  env_matrix:
  - PUPPET_GEM_VERSION="~> 2.7.0"
  - PUPPET_GEM_VERSION="~> 3.0.0"
  - PUPPET_GEM_VERSION="~> 3.1.0"
  excludes:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 2.7.0"
  - rvm: ruby-head
    env: PUPPET_GEM_VERSION="~> 2.7.0"
Gemfile:
  optional:
  - gem: mocha
spec/spec_helper.rb:
  unmanaged: true
